export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_DETAIL = 'GET_CHARACTERS_DETAIL';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const GET_USERS = 'GET_USERS';
export const SEARCH_EMAIL = 'SEARCH_EMAIL';